### ISSUE TITLE
MySql driver

### ISSUE THREAD

**Issue by hdhaheri** [QuasarApp/CQtDeployer#367]
When running the application on another machine using the generated DistributionKit folder, I get QMYSQL driver not loaded. I checked the plugins/sqldrivers folder and it has the driver. How to solve this issue. Thank you

**Comment by EndrII** [comment]
Thanks for question. 
The problem is that you do not have the mysql client in the distribution that is needed for the mysql driver to work.
this is usually solved by installing this client on a remote machine or adding the appropriate libraries to the distribution.

Solution 1. 
```
sudo apt-get install mysql-client-core-*
```

Solution 2. 
make cqtdeployer grab the mysql client
uses option *extraLibs*
```
cqtdeployer ... -extraLibs libmysqlclient
```
#### Attention
libmysqlclient will most likely be on the system, so you will need the cqtdeployer installed with the [installer](https://github.com/QuasarApp/CQtDeployer/releases/download/1.4.3/LinuxInstaller.run) and not from the snap store.

The fact is that the snap version does not currently have access to system libraries.

**Comment by EndrII** [comment]
I agree that all actions that solve your problem are not obvious and not convenient. according to this, I will take on the task  #371 of automating this entire process.

**Comment by EndrII** [comment]
Now cqtdeployer should be automatically copу the mysql client library into a distribution kit of you application.
