### ISSUE TITLE
Error: The deployment target requir Qt libs, but init qmake is failed.

### ISSUE THREAD

**Issue by jaylo30** [QuasarApp/CQtDeployer#373]
Hi,
First of all thank you for the program.

I am using ubuntu 18.04 and QT 5.9.5.

I want to run this on terminal:
cqtdeployer -bin MY_APP_NAME_IN_RELEASE_FOLDER  -qmake /usr/lib/qt5/bin/qmake

Note:
/usr/lib/qt5/bin/qmake -> FROM QT CREATOR -> options -> qt versions -> autodetected qt 5.9.5 -> qmake locations

Result:
Info: Deploy ...
Info: flag targetDir not  used. use default target dir :/root/Masaüstü/RELEASE/DistributionKit
Error: The deployment target requir Qt libs, but init qmake is failed.
Error: deploy is failed!

Note2:
root@ubuntu-pc:~/DEPLOY_TEST_1# qmake --version
QMake version 3.1
Using Qt version 5.9.5 in /usr/lib/x86_64-linux-gnu

What's the problem? 
Thanks.

**Comment by EndrII** [comment]
Hi, thanks of report. 
I see you use the qt library of system. And I assume that you are using cqtdeployer from the snap-store. Unfortunately at the moment, the snap version of cqtdeployer does not have access to the system files of the OS. This problem is known and she is waiting in line for solution #368.

## Solution 1
As a workaround, uninstall the snap version of cqtdeployer and install cqtdeployer from the installer.

## Solution 2

Install Qt from an[ official source](https://www.qt.io/download-open-source?hsCtaTracking=9f6a2170-a938-42df-a8e2-a9f0b1d6cdce%7C6cb0de4f-9bb5-4778-ab02-bfb62735f3e5) in user space. 

If you are unable to use the GUI, use the [console](https://github.com/miurahr/aqtinstall) utility to install Qt

**Comment by jaylo30** [comment]
Hi,

Solution 1 unfortunately did not work.

I will try solution 2, but I am afraid the project will not work again because i installed too many plugins and libs. 

Thanks for reply.

**Comment by EndrII** [comment]
could you run cqtdeployer with the option  -verbose 3
```
cqtdeployer -bin MY_APP_NAME_IN_RELEASE_FOLDER -qmake /usr/lib/qt5/bin/qmake -verbose 3

```
and show me output log please

**Comment by jaylo30** [comment]
I try it on another pc and it's work perfect :) 

Thank you so much.
