### ISSUE TITLE
v1.5: Feature request: do not generate "runScript" when it is not needed

### ISSUE THREAD

**Issue by pzhlkj6612** [QuasarApp/CQtDeployer#519]
**Is your feature request related to a problem? Please describe.**
Sometimes I want to deploy my program and all load-time dynamic linking libraries ("Qt5Core.dll", "libstdc++-6.dll", etc.) into one directory, and then package them into an installer with Inno Setup or a single executable file with Enigma Virtual Box. In this case, the runScript is redundant since my program can directly find all required libraries.

**Describe the solution you'd like**
Don't generate "runScript" when it is not needed.
Obviously, if certain options are present (e.g., `-libOut` and `-binOut` ) , "runScript" is needed because the deployed program can't find libraries without the correct `PATH` .

**Describe alternatives you've considered**
none.

**Additional context**
For v1.5 .
Related to #486 and #487 ?

**Comment by EndrII** [comment]
hmm.
The fact is that I specifically removed the check for disabling startup scripts, since without them the applications will not have access to the cqtdeployer variables, and this also reduces the difference in distributions between Linux and Windows.
this is useful if you are doing a distribution for different platforms.

In your case, it makes sense to turn off scripts. I think we need to add the noRunScripts option, which would turn off the creating of the scripts.

**Comment by sufuk** [comment]
Hello, I really need this feature, whats the status?

**Comment by EndrII** [comment]
Hi  @sufuk 
do you sure that you cannot solve your problem by running a bat script?

**Comment by EndrII** [comment]
@sufuk  If you want to disable create automaticity shortcuts then please see the our new documentation page about it.
This page added in the #565  PR.
