### ISSUE TITLE
ошибка сегментирования в сгенерированном скрипте запуска приложения

### ISSUE THREAD

**Issue by avttrue** [QuasarApp/CQtDeployer#574]
**ОС**
Собирается на `5.4.0-72-generic #80-Ubuntu`
Запускается на `AstraLinux 1.6 4.15.3-2-generic #astra25`

**Сборка дистрибутива**
`cqtdeployer -bin MYAPP deploySystem-with-libc noTranslations` (deploySystem-with-libc используется, чтобы попала библиотека libm.so.6)

**Сообщение в ОС**
`/../../MYAPP.sh : строка 13: 2427 Ошибка сегментирования "$BASE_DIR/bin/MYAPP" "$@"`
[cichorium.zip](https://github.com/QuasarApp/CQtDeployer/files/6334575/cichorium.zip)

**Comment by EndrII** [comment]
Please do not use the **deploySystem-with-libc** option because this option will copy low lvl libraries into your distribution and which leads to incompatibility errors on other distributions.
The **libc.so.6** library should be distributed with **Astra Linux 1.6** but not your program.

1. I recommends do not use any system libraries in your distribution.  If you want to add custom library to you distribution and you known that this library contains in your system environment but not contains in your git repository then you need to use the **-extraLibs** option. 

### Example :
```
cqtdeployer -bin myApp -qmake path/to/myQMake -extraLibs myLibsPatterName1,myLibsPatterName2 
```

2. If your target OS system is Astra linux 1.6 then best to build the project on Astra 1.6 to have maximum binary compatibility. 
But your case should be work. **ubuntu 18.04 > Astra 1.6** if you disable deploy system options.

**Comment by avttrue** [comment]
Thanks! `-extraLibs` - that helped me.

**Comment by andr1312e** [comment]
Работает все, добавь в параметры пункт noStrip:

`sudo /home/user/CQtDeployer/1.5/cqtdeployer.sh force-clear noStrip noTranslations deploySystem -bin ./build/untitled -qmake /home/user/Qt5.12.11/5.12.11/gcc_64/bin/qmake`

**Comment by avttrue** [comment]
Да уж разобрался, но спасибо.
