### ISSUE TITLE
Create Desktop shotcut after install completed

### ISSUE THREAD

**Issue by MMucka** [QuasarApp/CQtDeployer#680]
I want to ask, if it is possible to choose whether install wizard will create Desktop shotcut for easy access.
It should be possible by custom script, but I want to know, if there is some easyer way.

Thank you
Regards

**Comment by EndrII** [comment]
Hi 

In current time CQtDeployer tool automatically create shortcuts in a system menu of applications. 
* Linux is  **menu applications**
* Windows is **start menu**  

You can disable generate shortcuts using the **-disableShortCut** option
```bash
cqtdeployer ... -disableShortCut executableName
```

But not support creating shortcuts in desktop.

**Comment by EndrII** [comment]
Sorry. but i checked our code and in Windows platform cqtdeployer automatically generate shortcut to desktop.
Linux not support desktop shortcuts, because linux do not have one standart for the desktop locations. Many distributions use the ~/Desktop location for shortcuts but not all. So we can't to add support automaticaly generation shortcuts for desktop on Linux platforms. 
But you can create your custom script for creating desktop file for your application or use custom qifw template with code that will create desktop shortcat. 
  
See qifw templates [here](https://github.com/QuasarApp/CQtDeployer/blob/main/Deploy/Distributions/Templates/qif/packages/default/meta/installscript.qs) or official [documentation](https://doc.qt.io/qtinstallerframework/qtinstallerframework-startmenu-example.html). 
and you can see how to generate Linux Shortcut [here](https://linuxconfig.org/how-to-create-custom-desktop-files-for-launchers-on-linux).

And you can check how to use custom qifw template in cqtdeployer [here](https://quasarapp.ddns.net:3031/docs/QuasarApp/CQtDeployer/latest/md_md_en_QIF.html)

**Comment by MMucka** [comment]
Thank you very much for this information. 
I need that shortcut for Ubuntu, so I will try to create qifw template.

Best regards
