### ISSUE TITLE
The desktop and launch bar can be invoked using shortcuts

### ISSUE THREAD

**Issue by Six-6Chen** [QuasarApp/CQtDeployer#694]
I would like to be able to launch the software on the desktop after installation

**Comment by EndrII** [comment]
Do you want to add automatically deployed shortcuts to Windows desktop, right ?

**Comment by Six-6Chen** [comment]
YES

**Comment by EndrII** [comment]
> I installed deb on linux but postinst doesn't generate desktop files in applications and desktop

generate shortcut after install from deb pacakge it is troube because diferent distros hs diferent pathes of desktop location. and desctop usaly located in users space but deb pacakge install using root. 
I just can't check for what user i should add shortcut.

deb packge can generate shorctuts  to application menu only.

**Comment by EndrII** [comment]
i close this issue because a required feature is impossible to implement
