### ISSUE TITLE
Deploy an application that uses both normal QML files and Qt Design Studio

### ISSUE THREAD

**Issue by robosina** [QuasarApp/CQtDeployer#748]
Hello, my application uses both **QML** and **Qt Design studio** simultaneously, and I have asked a similar question in the [gist](https://gist.github.com/EndrII/a96ff2b4d293133067ac2a1f5dad5fe8#gistcomment-4427160) of the repository regarding deployment of an application that uses multiple QML roots. However, I am observing that the application always uses the one to which `qmake` points (I presume).

 This is a unique feature because both of these two have different versions of `qmake`, libraries, and so on. What is the best way to deploy such an application? Is it possible to deploy such an application using the current `CQtDeployer`?

**Comment by EndrII** [comment]
Hm. Do you link your application on the one executable or multiple ?

If you use one executable with depends on different qt versions (for example qt 6.1 and 6.4) then deploy is impossible because your app will be contained links to major qt versions.
For example
myApp -> libQtCore.6, bot not libQtCore.6.4
so qt 6.4 and qt6.1 has one name of the lib, it is libQtCore.6, If you run this app probably it will crash...

I think you have only one solution for your case. It is a static link of two separated gui modules.

For example,
you create gui1.so and gui2.so. The both your libs link all dependencies as a static lib. Include qml and plugins


How to do it :

1. build your first qt as a static framework
2. build your second qt as a static framework
3. create a first gui library as a shared model, it will be depended on the static first qt. (Contains in gui1.so)
4. create a second gui library as a shared modele, it will be depended on the static second qt. (Contains in gui2.so)
5. create your executable that depends on the both gui libs,

your GUI libs should be works using interfaces. Because they qt's version will be different and incompatible 


Did you manage to run your application from qt creator?
Does it work correctly? Do you have random crashes?

**Comment by robosina** [comment]
Sorry for the late response, this seems to be fixed in newer versions. In newer versions, `Qt Design Studio` is built alongside the projects (i.e. With `fetchContent` in Cmake, the components can be retrieved and built as normal QML files, so we don't need any additional things for deploying that files). It appears that this issue is now unrelated to this project and can be closed.
